name: golang
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        # https://github.com/actions/cache/issues/720#issuecomment-1030412967
        timeout-minutes: 5
        continue-on-error: true
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/pre-commit
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout=5m

      # https://github.com/pre-commit/action
      - uses: pre-commit/action@v3.0.0

      - run: scripts/check_gotidy.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        # https://github.com/actions/cache/issues/720#issuecomment-1030412967
        timeout-minutes: 5
        continue-on-error: true
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/pre-commit
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: go test
        run: |
          go test -race -timeout=10m -coverpkg=./... -covermode atomic -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        # this line will prevent forks of this repo from attempting to upload coverage
        if: github.repository == 'airplanedev/cli'
        run: bash <(curl -s https://codecov.io/bash)

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: snyk/actions/setup@master
      - name: Run snyk scan
        run: |
          snyk test --severity-threshold=high
          snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
